---
- name: create kubeconfig directory
  file:
    path: "{{ homedir }}/.kube"
    state: directory

- name: create temp krew directory
  file:
    path: "/tmp/krew"
    state: directory

- name: download krew release files
  get_url:
    dest: "/tmp/krew/krew.tar.gz"
    url: "https://github.com/kubernetes-sigs/krew/releases/latest/download/krew.tar.gz"

- name: unpackage krew release
  unarchive:
    src: "/tmp/krew/krew.tar.gz"
    dest: "/tmp/krew"

- name: run krew install step
  shell: |
    /tmp/krew/krew-darwin_amd64 install
  args:
    creates: "{{ homedir }}/.krew"

- name: ensure bin dir exists
  file:
    path: "{{ homedir }}/.bin"
    state: directory

- name: move krew binary into homedir bin
  copy:
    dest: "{{ homedir }}/.bin/krew"
    src: /tmp/krew/krew-darwin_amd64
    mode: "0755"

- name: install krew plugins
  shell: "/tmp/krew/krew-darwin_amd64 install {{ item }}"
  args:
    creates: "{{ homedir }}/.krew/bin/kubectl-{{ item }}"
  with_items:
    - ctx
    - konfig
    - ns
