---
- name: download binaries
  get_url:
    dest: "/tmp/{{ item.name }}{{ item.package_ext | d('') }}"
    url: "{{ item.url }}"
  with_items: "{{ misc_binaries }}"

- name: unpackage downloaded archives
  unarchive:
    dest: "/tmp"
    src: "/tmp/{{ item.name }}{{ item.package_ext }}"
  with_items: "{{ misc_binaries | selectattr('packaged') | list }}"

- name: ensure bin dir exists
  file:
    path: "{{ homedir }}/.bin"
    state: directory

- name: move donwloaded binaries into homedir bin
  copy:
    dest: "{{ homedir }}/.bin/{{ item.name }}"
    src: "/tmp/{{ item.name }}"
    mode: "0755"
  with_items: "{{ misc_binaries }}"
