---
- name: copy neovim config
  copy:
    dest: "{{ homedir }}/.config/nvim/init.lua"
    src: ".config/nvim/init.lua"
    mode: "0644"

- name: install nvim plugins
  command:
    cmd: "nvim +PackerInstall +qa"
    creates: "{{ homedir }}/.local/share/nvim/site/pack/packer/start/packer.nvim"
