---
- name: copy tmux config
  copy:
    dest: "{{ homedir }}/.tmux.conf"
    src: ".tmux.conf"

- name: install teamocil
  gem:
    name: teamocil
    state: present
    user_install: true

- name: create teamocil dir
  file:
    path: "{{ homedir }}/.teamocil"
    state: directory

- name: create teamocil completions
  copy:
    dest: "{{ homedir }}/.config/fish/completions/teamocil.fish"
    src: ".config/fish/completions/teamocil.fish"
