add_newline = false
prompt_order = [
    "package",
    "dotnet",
    "golang",
    "java",
    "nodejs",
    "python",
    "ruby",
    "rust",
    "kubernetes",
    "line_break",
    "directory",
    "git_branch",
    "line_break",
    "character",
]

[hostname]
ssh_only = false

[kubernetes]
symbol = "⛵ "
disabled = false

[line_break]
disabled = false

[username]
show_always = true
