add_newline = false
prompt_order = [
    "username",
    "hostname",
    "kubernetes",
    "directory",
    "git_branch",
    "git_state",
    "git_status",
    "package",
    "dotnet",
    "golang",
    "java",
    "nodejs",
    "python",
    "ruby",
    "rust",
    # "nix_shell",
    # "conda",
    # "memory_usage",
    # "aws",
    # "env_var",
    # "cmd_duration",
    # "jobs",
    # "battery",
    # "time",
    "line_break",
    "character",
]

[hostname]
ssh_only = false

[kubernetes]
symbol = "⛵ "
disabled = false

[line_break]
disabled = false

[username]
show_always = true
