add_newline = false
format = """\
    $package\
    $dotnet\
    $golang\
    $java\
    $nodejs\
    $python\
    $ruby\
    $rust\
    $kubernetes\
    $directory\
    $git_branch\
    $line_break\
    $character\
"""

[hostname]
ssh_only = false

[kubernetes]
symbol = "⛵ "
disabled = false

[line_break]
disabled = false

[username]
show_always = true
